on:
  push:
    branches:
       - master

jobs:
  test_rstudio_container_run:
    name: Test VSCode container run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build docker image
        run: >
          cd vscode && 
          make build
      - name: Run docker container in actions run
        run: > 
          cd vscode &&
          make run PASSWORD="${{ secrets.VSCODE_PASSWORD }}"
