on:
  push:
    branches:
       - master

jobs:
  test_rstudio_container_run:
    name: Test RStudio container run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: > 
          apt-get update -y

          apt-get install -y git \
            ca-certificates \
            curl \
            gnupg \
            lsb-release \
            wget \ 
            make
          
          curl -fsSL \
            https://download.docker.com/linux/ubuntu/gpg | \ 
          gpg --dearmor -o \ 
            /usr/share/keyrings/docker-archive-keyring.gpg
          
          echo \
            "deb [ \ 
              arch=$(dpkg --print-architecture) \ 
              signed-by=/usr/share/keyrings/docker-archive-keyring.gpg \
            ] \ 
            https://download.docker.com/linux/ubuntu \ 
            $(lsb_release -cs) \ 
            stable" | \ 
          tee /etc/apt/sources.list.d/docker.list > /dev/null

          apt-get update -y

          apt-get install -y docker-ce \
          docker-ce-cli \
          containerd.io

          groupadd docker
          usermod -aG docker root

          systemctl enable docker.service
          systemctl enable containerd.service

          curl -L \ 
            "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \ 
            -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
      - name: Run docker container in actions run
        run: > 
          cd vpn &&
          make run
