on:
  push:
    branches:
       - master

jobs:
  test_rstudio_container_run:
    name: Test VSCode container run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build docker image and push
        run: >
          cd vscode && 
          make build && 
          make push
