on:
  push:
    branches:
       - master

jobs:
  test_rstudio_container_run:
    name: Test RStudio container run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run docker container in actions run
        run: > 
          cd rstudio &&
          make run
